In [1]:
from scipy import sparse
train_x=sparse.load_npz('final_train_x.npz')

In [2]:
test_x=sparse.load_npz('final_test_x.npz')

In [3]:
print(train_x.shape,test_x.shape)

(2903024, 300001) (110775, 300001)


In [4]:
import pandas as pd
import csv
train_y=pd.read_csv('train.csv',escapechar='\\',quoting=csv.QUOTE_NONE)
train_y=train_y['BROWSE_NODE_ID']
print(train_y.shape)
train_y

(2903024,)


0                0
1                1
2                2
3                3
4                4
            ...   
2903019       1040
2903020      15199
2903021    1044933
2903022      14790
2903023       1213
Name: BROWSE_NODE_ID, Length: 2903024, dtype: int64

In [5]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()

In [6]:
import numpy as np

In [7]:
for j in range(100000,2903023,100000):
    print(j-100000,j)
    nb.partial_fit(train_x[j-100000:j,:],train_y[j-100000:j],classes=np.unique(train_y))
    

0 100000
100000 200000
200000 300000
300000 400000
400000 500000
500000 600000
600000 700000
700000 800000
800000 900000
900000 1000000
1000000 1100000
1100000 1200000
1200000 1300000
1300000 1400000
1400000 1500000
1500000 1600000
1600000 1700000
1700000 1800000
1800000 1900000
1900000 2000000
2000000 2100000
2100000 2200000
2200000 2300000
2300000 2400000
2400000 2500000
2500000 2600000
2600000 2700000
2700000 2800000
2800000 2900000


In [8]:
nb.partial_fit(train_x[2900000:,:],train_y[2900000:])

MultinomialNB()

In [9]:
result=nb.predict(test_x)

In [10]:
type(nb)

sklearn.naive_bayes.MultinomialNB

In [11]:
print(result.shape)
print(result[:50])

(110775,)
[  74   89  993    4 1922    4    4  993    4 1024    4 1024 1295 2321
 1287  890  890  787   89  251 2594 1079 2594 1045    4  739 1024 1045
    4    4 1045  890  106    4    4 2229 2040 2229   55 1024 1024   89
 1045 1045 1045  413    4  796 1045    4]


In [12]:
import numpy as np

In [13]:
np.unique(result)

array([      0,       1,       4, ..., 2469860, 2602634, 2741191],
      dtype=int64)

In [14]:
dict={'BROWSE_NODE_ID':result}

In [15]:
import pandas as pd

In [16]:
id=[]
for j in range(1,110776):
    id.append(j)

In [17]:
dict={'PRODUCT_ID':id,'BROWSE_NODE_ID':result}

In [18]:
df=pd.DataFrame(dict)

In [19]:
len(id)

110775

In [20]:
result.shape

(110775,)

In [21]:
np.unique(result, return_counts=True)

(array([      0,       1,       4, ..., 2469860, 2602634, 2741191],
       dtype=int64),
 array([    3,    15, 18448, ...,     6,    16,    24], dtype=int64))

In [22]:
df.head()

PRODUCT_ID  BROWSE_NODE_ID
0           1              74
1           2              89
2           3             993
3           4               4
4           5            1922

In [23]:
df.to_csv('final_output.csv',index=False)